version: "2"

linters:
  enable:
    - bodyclose
    - copyloopvar
    - durationcheck
    - errcheck
    - errorlint
    - gocritic
    - gosec
    - govet
    - ineffassign
    - makezero
    - misspell
    - modernize
    - nilerr
    - perfsprint
    - prealloc
    - staticcheck
    - unconvert
    - unused
    - usestdlibvars
    - wastedassign

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
